url: "http://smartcorelib.org"
tagline: "Rust Machine Learning"
email: smartcorelib@gmail.com
author: SmartCore Developers
baseurl: "/0.2.0"
title: "SmartCore"
years_updated: 2020-2021
smartcore_version: 0.2.0
# api_base_url: "https://docs.rs/smartcore/0.2.0/smartcore"
api_base_url: "http://localhost:8080/smartcore"

analytics-google: 'G-D1L0JVQB04'

exclude:
  - scripts
  - smartcorelib.code-workspace

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
